title: My Blog 2
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/testsite"
url: "https://akekyzst.github.io"
twitter_username: jekyllrb
github_username:  jekyll
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed